Add optional metadatacompliancetype field to object-templates
open-cluster-management/config-policy-controller pull request #202
Opened 2021-12-14 15:52 UTC by willkutler

https://github.com/open-cluster-management/backlog/issues/17904

Signed-off-by: Will Kutler <wkutler@redhat.com>

2021-12-14 19:07 UTC, ycao56 commented
/lgtm
/hold for others to take a look

2021-12-14 19:07 UTC, ycao56 approved these changes

2021-12-15 14:30 UTC, gparvin commented
Is there a good use case for:
```
    - complianceType: musthave
      metadataComplianceType: mustonlyhave
```

@willkutler  Can you link a doc pr to the issue if this will be documented?  Otherwise we'll probably forget to document this field.

2021-12-15 14:48 UTC, willkutler commented
@gparvin a use case for that would be if a user wants to use mustonlyhave to remove an existing label or annotation without changing the behavior of the rest of the policy. Should I be making a doc PR myself or just creating an issue for it?

2021-12-15 18:06 UTC, gparvin commented
@willkutler Just a doc issue I meant to say.  Thanks!

2021-12-15 18:07 UTC, gparvin approved these changes

2021-12-20 21:32 UTC, mprahl commented on test/e2e/case9_md_check_test.go
> +			utils.Kubectl("apply", "-f", case9PolicyYamlMultiAnnoNSCreate, "-n", testNamespace)
Where does this policy get cleaned up?

2021-12-20 21:47 UTC, willkutler commented
@mprahl added some changes based on your comments

2021-12-21 13:30 UTC, mprahl approved these changes
Nice!

2021-12-21 13:33 UTC, mprahl requested changes

2021-12-21 15:14 UTC, mprahl approved these changes
Nice!

2021-12-21 15:28 UTC, willkutler commented
Doc issue for this here: https://github.com/open-cluster-management/backlog/issues/18649

2021-12-22 14:27 UTC, willkutler commented
/unhold

2021-12-22 14:28 UTC, merged